name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Xcode (latest)
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
      
      - name: Type check
        run: npm run typecheck
      
      - name: Build
        run: npm run build
      
      - name: Debug xcresulttool version and capabilities
        run: |
          xcrun xcresulttool version
          xcrun xcresulttool --help
      
      - name: Check test fixtures exist
        run: |
          ls -la test/fixtures/
          echo "Using existing test fixtures for CI"
      
      - name: Test Core Components
        run: |
          # Run tests for core components with coverage
          npm test test/xcjson.test.ts test/validator.test.ts test/parser.test.ts test/cache.test.ts test/schema.test.ts -- --coverage
          
      - name: Test CLI Schema Command
        run: |
          # Test CLI schema command works with version-compatible xcresulttool
          echo "Testing schema command"
          node dist/index.js --schema | head -10
          echo "Schema command completed"
      
      - name: Validate schema drift
        run: |
          npm run build:types
          git diff --exit-code src/schema/ src/types/
      
      - name: Test CLI Help
        run: |
          node dist/index.js --help
          
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info