name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Xcode (latest)
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
      
      - name: Type check
        run: npm run typecheck
      
      - name: Build
        run: npm run build
      
      - name: Debug xcresulttool version and capabilities
        run: |
          xcrun xcresulttool version
          xcrun xcresulttool --help
          echo "Available commands:"
          xcrun xcresulttool help
      
      - name: Generate test fixture
        run: |
          cd example_project
          # Run tests to generate xcresult (expect failures)
          set +e
          xcodebuild test -workspace CalculatorApp.xcworkspace -scheme CalculatorApp -destination 'platform=iOS Simulator,name=iPhone 15' -resultBundlePath TestResult.xcresult
          set -e
          # Copy to test fixtures
          rm -rf ../test/fixtures/TestResult.xcresult
          cp -r TestResult.xcresult ../test/fixtures/
          ls -la ../test/fixtures/
      
      - name: Test Integration and CLI
        run: |
          # Run integration tests that use real xcresult files
          npm test test/integration.test.ts test/cli.test.ts -- --coverage
          
      - name: Test CLI with real fixture
        run: |
          # Test CLI with the generated xcresult
          node dist/index.js --path test/fixtures/TestResult.xcresult --pretty
          echo "Exit code: $?"
      
      - name: Validate schema drift
        run: |
          npm run build:types
          git diff --exit-code src/schema/ src/types/
      
      - name: Test CLI
        run: |
          node dist/index.js --schema
          
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info